<?php
require_once("inc/init.php");
require_once("inc/header2.php");
?>
 
 <section class="inner-intro bg-22 bg-overlay-black-70">
  <div class="container">
     <div class="row text-center intro-title">
           <div class="col-md-6 text-md-left d-inline-block">
             <h1 class="text-white">Notre parc </h1>
           </div>
           <div class="col-md-6 text-md-right float-right">
     </div>
  </div>
</section>

<section class="product-listing page-section-ptb">
 <div class="container">
  <div class="row">
   
     <div class="col-lg-12 col-md-12">
       
        <div class="row">



          <!-- INSERT NEW VEHICULES FROM HERE -->

          <!-- RENDRE CETTE PARTIE DYNAMIQUE -->
          <!-- SELECTIONNER EN BASE TOUTES LES VOITURES DISPO ET ITÉRER DANS LA CARD -->

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/mt03/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/mt03.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2008</li><li><i class='fa fa-cog'></i>'NAN </li><li><i class='fa fa-shopping-cart'></i> 28000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Yamaha MT-03</a><div class='separator'></div><div class='price'><span class='old-price'>3690€</span><span class='new-price'>3500€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/yamahaTricity/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/yamahaTricity.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2015</li><li><i class='fa fa-cog'></i>'NAN </li><li><i class='fa fa-shopping-cart'></i> 23000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Yamaha Tricity 125</a><div class='separator'></div><div class='price'><span class='old-price'>1890€</span><span class='new-price'>1790€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/classeV220dAvantGarde/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/classeV220dAvantGarde.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2016</li><li><i class='fa fa-cog'></i>'Automatique </li><li><i class='fa fa-shopping-cart'></i> 70000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Classe V220D 2.2 CDI</a><div class='separator'></div><div class='price'><span class='old-price'>35900€</span><span class='new-price'>34900€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/clio3Champagne/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/clio3Champagne.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2007</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 250 000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Clio 3 1.5 DCI 70</a><div class='separator'></div><div class='price'><span class='old-price'>1990€</span><span class='new-price'>1790€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/c4Rouge/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/c4Rouge.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2008</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 220 000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Citröen c4 1.6 HDI</a><div class='separator'></div><div class='price'><span class='old-price'>1990€</span><span class='new-price'>1890€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/c12017/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/c12017.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2017</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 36000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>C1 1.0 VTi 68 Feel</a><div class='separator'></div><div class='price'><span class='old-price'>8290€</span><span class='new-price'>7990€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/207Plus/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/207Plus.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2013</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 117000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>207 + </a><div class='separator'></div><div class='price'><span class='old-price'>5590€</span><span class='new-price'>5490€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/clio2Rxe/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/clio2Rxe.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2000</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 93000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Clio 2 1.2 RXE</a><div class='separator'></div><div class='price'><span class='old-price'>1890€</span><span class='new-price'>1790€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/206PlusTrendyGrey/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/206PlusTrendyGrey.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2010</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 36000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>206+ 1.1 Trendy</a><div class='separator'></div><div class='price'><span class='old-price'>5190€</span><span class='new-price'>4890€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/jaguar/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/jaguar.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2009</li><li><i class='fa fa-cog'></i>'Auto </li><li><i class='fa fa-shopping-cart'></i> 115000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Jaguar XF 3.0 V6 LUXE PREMIUM </a><div class='separator'></div><div class='price'><span class='old-price'>14900€</span><span class='new-price'>14500€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/c1White/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/c1White.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2012</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 60 000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Citröen c1 1.0 Attraction</a><div class='separator'></div><div class='price'><span class='old-price'>3690€</span><span class='new-price'>3490€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/rav4/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/rav4.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2010</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 140000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Toyota RAV4 2.2 D-4D Clean Power</a><div class='separator'></div><div class='price'><span class='old-price'>8100€</span><span class='new-price'>7900€</span></div></div></div></div>


          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/twingo3/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/twingo3.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2016</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 15000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Twingo 3 1.0 SCe 71 cv</a><div class='separator'></div><div class='price'><span class='old-price'>7690€</span><span class='new-price'>7590€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/c1Red/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/c1Red.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2012</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 60000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Citroën C1 1.0 Attraction</a><div class='separator'></div><div class='price'><span class='old-price'>4890€</span><span class='new-price'>4590€</span></div></div></div></div>


          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/206PlusWhite/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/206PlusWhite.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2011</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 42 000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Peugeot 206 + 1.1 Urban</a><div class='separator'></div><div class='price'><span class='old-price'>4790€</span><span class='new-price'>4390€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/206Urban2011/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/206Urban2011.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2011</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 115 000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>Peugeot 206 + 1.1 Urban</a><div class='separator'></div><div class='price'><span class='old-price'>3590€</span><span class='new-price'>3390€</span></div></div></div></div>

          <div class='col-lg-4'><div class='car-item gray-bg text-center'><div class='car-image'><img class='img-fluid' src='images/detail/big/206Trendy2012/1.jpg' alt=''><div class='car-overlay-banner'><ul> <li><a href='cars/206Trendy2012.html'><i class='fa fa-link'></i></a></li><!--<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>--></ul></div></div><div class='car-list'><ul class='list-inline'><li><i class='fa fa-registered'></i> 2012</li><li><i class='fa fa-cog'></i>'Manuelle </li><li><i class='fa fa-shopping-cart'></i> 72 000</li></ul></div><div class='car-content'><div class='star'><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star orange-color'></i><i class='fa fa-star-o orange-color'></i></div><a href='#'>206 + 1.4 Trendy 75 CH</a><div class='separator'></div><div class='price'><span class='old-price'>4990€</span><span class='new-price'>4790€ </span></div></div></div></div>


       </div>
     </div>
  </div>
</section>

<!--=================================
product-listing  -->
 
 
<!--=================================
 footer -->

<?php
require_once("inc/footer.php");
?>
